name: "Shot Scraper"
version: "0.1.1"
slug: "shot_scraper"
description: "Take website screenshots with shot-scraper"
url: "https://github.com/weidi/ha-addons/tree/main/shot-scraper"
startup: once
boot: manual_only
init: false
stdin: true
arch:
  - amd64
  - aarch64
map:
  - type: share
    read_only: false
options:
  url: ""
  output: "shot-scraper/output.png"
  auth_file: ""
  retries: 2
  args: ""
schema:
  url: "str"
  output: "str"
  auth_file: "str?"
  retries: "int"
  args: "str?"
